//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespositoryPattrenLabSwitch
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_MANUFACTURER
    {
        public string SETID { get; set; }
        public string MFG_ID { get; set; }
        public string DESCRSHORT { get; set; }
        public string DESCR60 { get; set; }
        public string UPN_TYPE_CD { get; set; }
        public string LOCALLY_OWNED_FLG { get; set; }
        public string GS1_GLN { get; set; }
    }
}
