//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RespositoryPattrenLabSwitch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWITCHDBEntities : DbContext
    {
        public SWITCHDBEntities()
            : base("name=SWITCHDBEntities")
        {
        }
       // public SWITCHDBEntities Instance { get { return new SWITCHDBEntities(); } }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PS_MANUFACTURER> PS_MANUFACTURER { get; set; }
    }
}
